cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, update_cart

urlpatterns = [
    url(r'^$', view_cart, name = 'view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name = 'add_to_cart'),
    url(r'^update/(?P<id>\d+)', update_cart, name = 'update_cart'),
]

pictures_on_the_wall/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views import static
from authentication.views import logout, login, registration, user_profile
from home.views import index, index_no_intro
from authentication import urls as authentication_urls
from products import urls as products_urls
from checkout import urls as checkout_urls
from .settings import MEDIA_ROOT
from cart import urls as cart_urls
from search import urls as search_urls
from artist import urls as artist_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^home$', index_no_intro, name='home'),
    url(r'^home/(?P<filter_group>\w+)', index_no_intro, name='home'),
    url(r'^authentication/', include(authentication_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^checkout/', include(checkout_urls)),
    url(r'^cart/', include(cart_urls)),
    url(r'^search/', include(search_urls)),
    url(r'^artist/', include(artist_urls)),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
]

products/urls.py
from django.conf.urls import url, include
from products.views import all_products, product_details, filtered_products, file_upload, modify_artwork, delete_artwork, delete_confirm, rate_artwork, sort_and_filter, like_artwork

urlpatterns = [
    url(r'^$', all_products, name = 'products'),
    url(r'^filtered/(?P<filter_group>\w+)/(?P<filter_name>\W*\w+)', filtered_products, name = "filtered_products"),
    url(r'^product_details/(?P<id>\d+)', product_details, name = "product_details"),
    url(r'^upload/', file_upload, name = "file_upload"),
    url(r'^modify/(?P<id>\d+)', modify_artwork, name = "modify_artwork"),
    url(r'^delete/(?P<id>\d+)', delete_artwork, name = "delete_artwork"),
    url(r'^delete_confirm/(?P<id>\d+)', delete_confirm, name = "delete_confirm"),
    url(r'^rate/(?P<id>\d+)', rate_artwork, name = "rate_artwork"),
    url(r'^rate/', rate_artwork, name = "rate_artwork"),
    url(r'^sort/', sort_and_filter, name = "sort"),
    url(r'^like/', like_artwork, name = "like_artwork"),
]

products/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.contrib.auth.validators import UnicodeUsernameValidator

# Create your models here.


class Category(models.Model):
    """Artwork (product) categories model """
    category_name = models.CharField(max_length=32, default='')
    category_description = models.TextField()

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = "Categories"


class Badge(models.Model):
    """ Badges for Artists (eg. hobby, advanced, master, pro...) """
    badge_name = models.CharField(max_length=16)
    badge_logo = models.ImageField(upload_to='images')

    def __str__(self):
        return self.badge_name


class Artist(models.Model):
    """ Model for the Artists uploading their artwork to the site """
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    artist_name = models.CharField(max_length=16, validators=[UnicodeUsernameValidator])
    # artist_name is the display name for the artists, named in this format to match other filter name structures
    avatar = models.ImageField(upload_to='images')
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    address = models.CharField(max_length=64, default='')
    wants_marketing = models.BooleanField(default=True)
    wants_newsletter = models.BooleanField(default=True)
    assigned_user = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.artist_name


class Technology(models.Model):
    """ Model for valiable printing technologies. Each artwork is assigned to all relevant print technologies"""
    technology_name = models.CharField(max_length=32)
    technology_description = models.TextField
    technology_price_coefficient = models.DecimalField(max_digits=4, decimal_places=2, null=True)

    def __str__(self):
        return self.technology_name

    class Meta:
        verbose_name_plural = "Technologies"


class Room(models.Model):
    """ Model for assigning artwork to certain room types """
    room_name = models.CharField(max_length=16, default='')

    def __str__(self):
        return self.room_name

def image_size_validator(image):
    size = image.file.size
    limit_mb = 1
    if size > limit_mb * 1024 * 1024:
        raise ValidationError(f"! The maximum file size is {limit_mb} MB (for the prototype, commercial version will be different) !")
    # maybe add min limit 600 pixel for longer side 

class Format(models.Model):
    """ Model for Picutre formats, aka aspect ratio """
    format_name = models.CharField(max_length=16, default='')
    format_description = models.CharField(max_length=60, default='')

    def __str__(self):
        return self.format_name


class Product(models.Model):
    """The Artwork (Product) model, contains all the artworks """
    title = models.CharField(max_length=32, default='')
    description = models.TextField()
    image = models.ImageField(upload_to='images', validators=[image_size_validator])
    base_repro_fee = models.DecimalField(max_digits=6, decimal_places=2, default=4.99)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='')
    room = models.ManyToManyField(Room)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, default='')
    aspect_ratio = models.ForeignKey(Format, on_delete=models.CASCADE, default='', null=True)
    max_print_size = models.CharField(max_length=16, default='')
    available_technologies = models.ManyToManyField(Technology)
    num_of_likes = models.IntegerField(default=0)
    num_of_orders = models.IntegerField(default=0)
    num_of_views = models.IntegerField(default=0)
    date_uploaded = models.DateTimeField(auto_now=True)
    hashtag = models.CharField(max_length=32, default='', null=True)

    def __str__(self):
        return self.title

# delete this from production version, it is just for GitPod to avoid 'Problems':
    objects = models.Manager()


class Rating(models.Model):
    """ Model for Products ratings: """
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default='')
    rating = models.IntegerField()
    #userid (of the rater to prevent double rating) --- TO BE ADDED LATER


class Size(models.Model):
    """ Model for exact picture sizes in cm or inch """
    format_name = models.ForeignKey(Format, on_delete=models.CASCADE, default='')
    size_name = models.CharField(max_length=16, default='10 x 15 cm')
    longer_side = models.DecimalField(max_digits=6, decimal_places=2)
    shorter_side = models.DecimalField(max_digits=6, decimal_places=2, default=10)

    def __str__(self):
        return self.size_name

class Hashtag(models.Model):
    """ Model for Products ratings: """
    hashtag = models.CharField(max_length=32, default='')

    def __str__(self):
        return self.hashtag

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Product, Category, Hashtag, Rating, Artist, Size, Format, Technology
from .forms import FileUploadForm  # probably superseded, to be deleted
from .forms import EditProductFormOne, EditProductFormThree, RatingForm
from artist.forms import ArtistProfileForm
from django.contrib.auth.decorators import login_required
from pictures_on_the_wall.utils import special_filter, get_the_ratings_for
from django.contrib import messages
from django.contrib.auth.models import User
from .utils import image_manipulation, create_size_entries

# Create your views here.


def all_products(request):
    """ The view rendering a page with all products listed """
    all_the_products = Product.objects.all()
    # sort options can be
    sort_options = [
        'num_of_views',
        'num_of_likes',
        'date_uploaded',
        'num_of_orders',
        # 'rating', out of scope in this phase
    ]

    sort_by = sort_options[0]

    context = {
        "products": all_the_products,
        'filter_group': '',
        'filter_name': '',
        'sort_by': sort_by
    }
    return render(request, "products.html", {"data": context})


def product_details(request, id):
    """ The view rendering the page for one selected
    product and all of its details """
    selected_product = get_object_or_404(Product, id=id)
    
    # get existing number of views, increment and update model
    number = selected_product.num_of_views + 1
    Product.objects.filter(pk=id).update(num_of_views=number)

    # filtering all the relevant ratings from the Rating model:
    ratings_data = get_the_ratings_for(selected_product)

    # filtering all the sizes from the Size model:
    sizes = Size.objects.filter(format_name=selected_product.aspect_ratio)

    technologies = Technology.objects.all()

    # Bundling the data for the template to a dictionary:
    pass_to_template = {
        "selected_prod": selected_product,
        "ratings_data": ratings_data,
        'sizes': sizes,
        'technologies': technologies,
    }
    return render(
        request,
        "product_details.html",
        {"pass_to_template": pass_to_template}
    )


def filtered_products(request, filter_group, filter_name):
    """ The view rendering a page for all products (Artwork)
    filtered by a user selected criteria """

    # Call my helper function in utils.py to run the filter if there is filter
    if filter_group and filter_name:
        filtered_products = special_filter(filter_group, filter_name)
    else:
        filtered_products = Product.objects.all()

    # sort options can be
    sort_options = [
        'num_of_views',
        'num_of_likes',
        'date_uploaded',
        'num_of_orders',
        # 'rating',
    ]
    sort_by = sort_options[0]

    context = {
        "products": filtered_products,
        'filter_group': filter_group,
        'filter_name': filter_name,
        'sort_by': sort_by
    }
    return render(request, "products.html", {"data": context})


@login_required
def file_upload(request):
    """ The view rendering the page that explains how to become a contributor
    and upload an image, as well as the form for file upload"""
    #similar to modify_upload() view, see comments there for understanding

    if request.method == 'POST':
        edit_form_one = EditProductFormOne(request.POST, request.FILES)
        edit_form_three = EditProductFormThree(request.POST)

        set_artist = Artist.objects.filter(assigned_user=request.user)
        set_artist = set_artist.values('id')[0]['id']

        if edit_form_one.is_valid() and edit_form_three.is_valid():
            uploaded_file = request.FILES['image']
            image_data = image_manipulation(uploaded_file)
            new_product = edit_form_one.save(commit=False)
            new_hashtag, created = Hashtag.objects.get_or_create(hashtag=edit_form_three.cleaned_data['hashtag'])
            new_product.hashtag = new_hashtag.hashtag
            new_product.aspect_ratio = Format.objects.get(id=image_data['format_id'])
            new_product.max_print_size = image_data['longer_side']
            new_product.save()
            edit_form_one.save_m2m()

            return redirect('dashboard')
        else:
            print(f"file upload form isn't valid  - no file saved")

    else:
        try:
            # First check whether the user has an Artist profile:
            set_artist = Artist.objects.filter(
                assigned_user=request.user).values('id')[0]['id']
        except:
            # No Artist exists for the current user -> redirect them to create
            # with a message about the reason
            messages.success(request, "In order to be able to upload an artwork you need an Artist profile. Please create yours!")
            artist_form = ArtistProfileForm(
                initial={'assigned_user': request.user.id})
                # create a blank form with the artist prepopulated with a HiddenInput
            return render(request, 'artist_profile.html', {'artist_form': artist_form})
        
        edit_form_one = EditProductFormOne(initial={'artist': set_artist})
        edit_form_three = EditProductFormThree()
    # get all the hashtags from the model and prepare a list for autocomplete in JS
    hashtags = []
    for hashtag in Hashtag.objects.all().values('hashtag'):
        hash = hashtag['hashtag']
        hashtags.append(hash)
        # [0]['hashtag']

    return render(
        request,
        'upload.html',
        {
            'edit_form_one': edit_form_one,
            'edit_form_three': edit_form_three,
            'hashtags': hashtags,
        }
    )


def modify_artwork(request, id):
    """ The view rendering a page for modifying an already uploaded artwork\n
    pre-populates a form with the product selected by the user and saves the POST"""
    selected_product = get_object_or_404(Product, id=id)

    if request.method == 'POST':
        # If the form is being submitted:
        # create a form instance and populate it with data from the request:

        edit_form_one = EditProductFormOne(request.POST, request.FILES, instance=selected_product)
        edit_form_three = EditProductFormThree(request.POST, instance=selected_product)
        if edit_form_one.is_valid() and edit_form_three.is_valid():
            # get the file from the request
            uploaded_file = request.FILES['image']
            # send it to my Pillow utility function to process
            image_data = image_manipulation(uploaded_file)
            # get an object that hasn’t yet been saved to the database
            new_product = edit_form_one.save(commit=False)
            # create the new hashtag in the Hashtag model only if doesn't exist
            clean_hash = edit_form_three.cleaned_data['hashtag']
            new_hashtag, created = Hashtag.objects.get_or_create(hashtag=clean_hash)
            # add the hashtag to the product's hashtag field in Product model
            new_product.hashtag = new_hashtag.hashtag
            # save the extra fields:
            new_product.aspect_ratio = Format.objects.get(id=image_data['format_id'])
            new_product.max_print_size = image_data['longer_side']
            # ... more to be done here ... 
            # save the modifications
            new_product.save()
            # Now, save the many-to-many data for the form:
            edit_form_one.save_m2m()
            
            # The #hashtags need to be handled here ...  - TO BE IMPLEMENTED...
            return redirect('dashboard')
        else:
            print(f"file upload form isn't valid  - no file saved")

    else:
        # if the request is GET
        # Check whether the Product with the id belongs to the user
        set_artist = Artist.objects.filter(
                assigned_user=request.user)
        product_artist = selected_product.artist
        if set_artist.values('id')[0]['id'] == product_artist.id:
            edit_form_one = EditProductFormOne(instance=selected_product)
            edit_form_three = EditProductFormThree(instance=selected_product)
        else:
            messages.error(request, "It's interesting how you ended up here... ")
            messages.error(request, "... either something went wrong on our side or you are trying to be cheeky.")
            return redirect(reverse('home'))
    
    # get all the hashtags from the model and prepare a list for autocomplete in JS
    hashtags = []
    for hashtag in Hashtag.objects.all().values('hashtag'):
        hash = hashtag['hashtag']
        hashtags.append(hash)
    
    return render(request, 'modify.html',
        {
            'edit_form_one': edit_form_one,
            'edit_form_three': edit_form_three,
            'product': selected_product,
            'hashtags': hashtags,
        })


@login_required
def delete_artwork(request, id):
    """ A function handling a deleting request for an artwork\n
    displaying a confirmation page if the user is aloowed to delete"""
    artwork = get_object_or_404(Product, pk=id)
    # first we check if the user is the "owner" of the image
    artist = artwork.artist
    user = request.user
    if artist.assigned_user == user:
        #if yes, we display the confirmation page
        return render(request, 'delete_confirm.html', {'product': artwork}) 
    else:
        # otherwise we let them know:
        messages.error(request, 'Sorry It seems you are trying to delete a product that is not yours...')
    
    user = User.objects.get(email=request.user.email)
    return render(request, 'profile.html', {"profile": user})


@login_required
def delete_confirm(request, id):
    """ Actually deleting after confirmation\n
    using a form with post method to confirm deletion """
    artwork = get_object_or_404(Product, pk=id)
    if request.method == 'POST':
        artist = artwork.artist

products/templates/delete_confirm.html
{% extends 'base.html' %}

{% block page_title %} | Delete confirmation{% endblock %}

{% block content %}

<div class="container page-wrapper">
    <div class="container">
        <div class="row my-2 my-md-4">
            <div class="col-10 offset-1 text-center">
                <h2>
                    <span> Do You really want to delete your</span>
                    <span style="color: red;">{{ product.title }}</span>
                    <span>titled artwork ???</span>
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-6 mx-auto text-center">
                <form action="{% url 'delete_confirm' product.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-warning" type="submit">Sure, Go ahead! Delete it!</button>

                </form>
            </div>
            <div class="col-6 mx-auto text-center">
                <a class="btn btn-info" href="{% url 'dashboard' %}">Oooops, no! Cancel!</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

products/templates/edit.html
{% extends 'base.html' %}

{% load bootstrap_tags %}

{% block page_title %}Upload{% endblock %}

{% block content %}

<div class="row container-fluid edit-container">
	<form class="container-fluid edit-form" enctype="multipart/form-data" action="{% url 'edit_artwork' %}" method="post">
		<legend>Upload / Edit Your Artwork</legend>
		{% csrf_token %}
		
		<div class="container-fluid text-center">
			<div class="row">
                <!-- Part 1 of 3 -- The picture displayed if edit mode + details and upload -->	
                <div class="col-12 col-md-7 edit-form-groups">
					<legend>Part one</legend>
					<div class="edit-image">
						<img src="" alt="">
                    </div>
					{{ edit_form_one.as_p }}
				</div>

					<!-- Part 3 of 3 -- #hashtags -->
				<div class="col-12 col-md-5">
					<legend>Part three</legend>
					<div class="edit-hashtags">
						<!-- two separate containers for selected and other already existing hashtags -->
						<div class="edit-selected-hashtags">
							<p>selected hashtags here</p>
							{{ edit_form_three }}
						</div>
						<div class="edit-other-hashtags">
							<p>other hashtags here</p>
						</div>
					</div>
				</div>
			</div>
		</div>
        <div class="hidden">
            <!-- {{ edit_form_hidden }} -->
        </div>
        <input class="edit-form-submit btn btn-primary" type="submit" value="Upload">
    </form>


		</div>



		{% endblock %}

products/templates/modify.html
{% extends 'base.html' %}

{% load bootstrap_tags %}

{% block page_title %} | Modify Artwork{% endblock %}

{% block style-tag %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block content %}
<div class="container page-wrapper">
	<div class="row container-fluid edit-container">
		<form class="container-fluid edit-form" enctype="multipart/form-data"
			action="{% url 'modify_artwork' product.id %}" method="post">
			<legend>Edit Your Artwork</legend>
			{% csrf_token %}

			<div class="container-fluid text-center">
				<div class="row">
					<!-- Part 1 of 2 The picture displayed if edit mode + hashtags -->
					<div class="col-12 col-md-7 edit-form-groups">
						<legend>Part one</legend>
						<div class="details-image-box">
							<img class="details-image" src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.id }}">
                        </div>
                        <div class="edit-selected-hashtags">
						{{ edit_form_three | as_bootstrap }}
                        </div>
					</div>

                    <!-- Part 2 of 2 the details -->
                    <div class="col-12 col-md-5">
                        <legend>Part two</legend>
                        <div class="edit-hashtags">
                            <div class="edit-selected-hashtags">
                                <p>selected hashtags here</p>
                                {{ edit_form_one | as_bootstrap }}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <input class="edit-form-submit btn btn-primary" type="submit" value="Upload">
        </form>
    </div>
</div>

<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    
    var mySource = {{ hashtags | safe }}
    
    $( "#id_hashtag" ).autocomplete({
        source: mySource
    });

</script>

{% endblock %}

products/templates/products.html
{% extends 'base.html' %}

{% load bootstrap_tags %}

{% block page_title %} | Products{% endblock %}

{% block content %}

<div class="container-fluid page-wrapper">
    <div class="row row-flex mx-3">

        <div class="container-fluid mx-auto">

            <section class="row filtering-row my-3">
            
                <div class="filter-dropdown col-12 col-sm-6 col-md-3">
                    <!-- SELECTING SORT CRITERIA -->
                    <form class="input-group mb-3" action="{% url 'sort' %}" method="GET" id="sort-form"> 
                        <input class="form-control" type="hidden" value="{{ data.filter_group }}" id="filter_group" name="filter_group">
                        <input class="form-control" type="hidden" value="{{ data.filter_name }}" id="filter_name" name="filter_name">
                        <label class="my-auto mr-2" for="sort_by">Sort by:</label>
                        <select class="form-control filter_group-select" id="sort_by" name="sort_by" onchange="this.parentNode.submit()">
                            {% if data.sort_by == 'num_of_views' %}
                                <option selected value="num_of_views">Most Viewed</option>
                                {% else %}
                                <option value="num_of_views">Most Viewed</option>
                            {% endif %}
                            {% if data.sort_by == 'num_of_likes' %}
                                <option selected value="num_of_likes">Most Liked</option>
                                {% else %}
                                <option value="num_of_likes">Most Liked</option>
                            {% endif %}
                            {% if data.sort_by == 'date_uploaded' %}
                                <option selected value="date_uploaded">Most Recent</option>
                                {% else %}
                                <option value="date_uploaded">Most Recent</option>
                            {% endif %}
                            {% if data.sort_by == 'num_of_orders' %}
                                <option selected value="num_of_orders">Most Purchased</option>
                                {% else %}
                                <option value="num_of_orders">Most Purchased</option>
                            {% endif %}
                            <!-- {% if data.sort_by == 'rating' %}
                                <option selected value="rating">Highest Rated</option>
                                {% else %}
                                <option value="rating">Highest Rated</option>
                            {% endif %} -->
                        </select>
                    </form>
                </div>

            </section>

            <section class="row image-display">
                <div class="image-display-container mx-2">
                    {% for product in data.products %}
                    <div class="products-image-box mb-3">
                        <a href="{% url 'product_details' product.id %}">
                            <img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{product.title}} image" class="products-image">
                        </a>
                        <div class="overlay overlay-title">
                            <p class="overlay-icon">
                                <span class="overlay-title-text">{{ product.title }}</span>
                            </p>
                        </div>
                        <div class="overlay overlay-rate">
                            <form method="GET" class="overlay-icon" title="Add Like! It's {{product.num_of_likes}} so far..." action="{% url 'like_artwork' %}">
                            {% csrf_token %}
                                <!-- the like button on the image that triggers the form submission -->
                                <a onclick="this.parentNode.submit();">
                                    <i class="far fa-thumbs-up"></i>
                                </a>
                                <!-- and hidden sending all the other info needed for rendering the page again -->
                                <input type="hidden" name="liked_product" value="{{ product.id }}"/> 
                                <input type="hidden" name="filter_group" value="{{ data.filter_group }}"/> 
                                <input type="hidden" name="filter_name" value="{{ data.filter_name }}"/> 
                                <input type="hidden" name="sort_by" value="{{ data.sort_by }}"/> 
                            </form>
                        </div>
                        <div class="overlay overlay-cart">
                            <form method="post" class="overlay-icon" title="Add To Shopping Cart" action="{% url 'add_to_cart' product.id %}">
                            {% csrf_token %}
                                <input type="hidden" name="name" value="value" /> 
                                <a onclick="this.parentNode.submit();">
                                    <i class="fas fa-cart-plus"></i>
                                </a>
                            </form>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </section>
        </div>
    </div>
</div>

<script>
var log_this = "{{ data.sort_by }}"
console.log("data: ", log_this)
</script>

{% endblock %}

products/templates/rate.html
{% extends 'base.html' %}

{% load bootstrap_tags %}

{% block page_title %} | Product Rating{% endblock %}

{% block content %}

<div class="container page-wrapper">
    <div class="container-fluid text-center">
        <div class="rating-image-container">
            <img src="{{ MEDIA_URL }}{{ product.image }}" alt="{{ product.title }} image" >
        </div>

        <div class="row mx-auto">
            <form class="rating-form col-12 col-md-6" action="{% url 'rate_artwork' product.id %}" method="post">
                <div class="row form-box">
                <!-- onchange="this.form.submit()" -->
                    {% csrf_token %}
                    <div class="rating-select col-6 my-auto p-2">
                        {{ rating_form.as_p }}
                    </div>
                    <div class="rating-submit col-6 my-auto p-2">
                        <button class="btn btn-sm btn-warning" type="submit">
                            <span>Submit Rating</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}